spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ods-remake
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_URL}
    username: ${ORACLE_USER}
    password: ${ORACLE_PWD}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

