CREATE TABLE users (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR2(255),
    email VARCHAR2(255),
    password VARCHAR2(255),
    status NUMBER(5) DEFAULT 0,
    activated_date TIMESTAMP,
    deactivated_date TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
